import tkinter as tk
Window=tk.Tk()
Window.title=("tkk")
Window.geometry=("2000x2000")

buttin5=tk.Button(Window,text="MAP",anchor="center")
buttin6=tk.Button(Window,text="HELP",anchor="center")
buttin7=tk.Button(Window,text="POKEDEX",anchor="center")
buttin4=tk.Button(Window,text="INVENTORY",anchor="center")
buttin3=tk.Button(Window,text="SHOP",anchor="center")
buttin2=tk.Button(Window,text="ROSTER",anchor="center")
Label1=tk.Label(text="POKEMON ADVENTURE")
Label2=tk.Label(text="MINI MAP")
map=tk.PhotoImage(file="main.png")
nintendo=tk.PhotoImage(file="logo.png")
minimap=tk.PhotoImage(file="minimap.png")
compass=tk.PhotoImage(file="compass.png")
label4= tk.Label(Window, image=compass)
label5 = tk.Label(Window, image=map)
label6 = tk.Label(Window, image=minimap)
label7 = tk.Label(Window, image=nintendo)

buttin2.place(x=520,y=150,width=80)
buttin3.place(x=520,y=200,width=80)
buttin4.place(x=520,y=275,width=80)
buttin5.place(x=520,y=175,width=80)
buttin6.place(x=520,y=225,width=80)
buttin7.place(x=520,y=250,width=80)
Label1.place(x=180,y=0)
Label2.place(x=520,y=30)
label4.place(x=10,y=470)
label5.place(x=10,y=30)
label6.place(x=500,y=50)
label7.place(x=220,y=490)

Window.mainloop()